"""add sequence to users.id

Revision ID: 5a9917489b4d
Revises: 812f0a428721
Create Date: 2025-09-18 19:36:41.618929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a9917489b4d'
down_revision: Union[str, Sequence[str], None] = '812f0a428721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SEQUENCE IF NOT EXISTS users_id_seq;")
    op.execute("ALTER SEQUENCE users_id_seq OWNED BY users.id;")
    op.execute("ALTER TABLE users ALTER COLUMN id SET DEFAULT nextval('users_id_seq');")
    op.execute("SELECT setval('users_id_seq', COALESCE((SELECT MAX(id) FROM users), 0) + 1, false);")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
