"""id_fullname

Revision ID: 79ed2d4c022b
Revises: 3f9868c07c77
Create Date: 2025-09-17 20:14:19.407826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79ed2d4c022b'
down_revision: Union[str, Sequence[str], None] = '3f9868c07c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluations',
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('evaluation_value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('evaluation_id')
    )
    op.create_index(op.f('ix_evaluations_evaluation_id'), 'evaluations', ['evaluation_id'], unique=True)
    op.drop_index(op.f('ix_evalutions_id'), table_name='evalutions')
    op.drop_table('evalutions')
    op.add_column('meetings', sa.Column('meeting_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_meetings_id'), table_name='meetings')
    op.create_index(op.f('ix_meetings_meeting_id'), 'meetings', ['meeting_id'], unique=True)
    op.drop_column('meetings', 'id')
    op.add_column('tasks', sa.Column('task_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.create_index(op.f('ix_tasks_task_id'), 'tasks', ['task_id'], unique=True)
    op.drop_column('tasks', 'id')
    op.add_column('teams', sa.Column('team_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.create_index(op.f('ix_teams_team_id'), 'teams', ['team_id'], unique=True)
    op.drop_column('teams', 'id')
    op.add_column('users', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'user_id')
    op.add_column('teams', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_teams_team_id'), table_name='teams')
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.drop_column('teams', 'team_id')
    op.add_column('tasks', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tasks_task_id'), table_name='tasks')
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.drop_column('tasks', 'task_id')
    op.add_column('meetings', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_meetings_meeting_id'), table_name='meetings')
    op.create_index(op.f('ix_meetings_id'), 'meetings', ['id'], unique=False)
    op.drop_column('meetings', 'meeting_id')
    op.create_table('evalutions',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('evaluation_name', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_index(op.f('ix_evalutions_id'), 'evalutions', ['id'], unique=False)
    op.drop_index(op.f('ix_evaluations_evaluation_id'), table_name='evaluations')
    op.drop_table('evaluations')
    # ### end Alembic commands ###
