"""relations

Revision ID: 8086e721a026
Revises: 79ed2d4c022b
Create Date: 2025-09-17 20:14:58.099293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8086e721a026'
down_revision: Union[str, Sequence[str], None] = '79ed2d4c022b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('task_rating', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'evaluations', 'tasks', ['task_rating'], ['task_id'])
    op.add_column('tasks', sa.Column('task_executor', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['task_executor'], ['user_id'])
    op.add_column('teams', sa.Column('team_admin', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teams', 'users', ['team_admin'], ['user_id'])
    op.add_column('users', sa.Column('member_of_team', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'teams', ['member_of_team'], ['team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'member_of_team')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'team_admin')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'task_executor')
    op.drop_constraint(None, 'evaluations', type_='foreignkey')
    op.drop_column('evaluations', 'task_rating')
    # ### end Alembic commands ###
