"""user_id_to_id_relations

Revision ID: 850314ce1a4b
Revises: d817b503d28b
Create Date: 2025-09-18 18:50:48.626037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '850314ce1a4b'
down_revision: Union[str, Sequence[str], None] = 'd817b503d28b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('task_rating', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'evaluations', 'tasks', ['task_rating'], ['task_id'])
    op.add_column('tasks', sa.Column('task_executor', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['task_executor'], ['id'])
    op.add_column('teams', sa.Column('team_admin', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teams', 'users', ['team_admin'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'team_admin')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'task_executor')
    op.drop_constraint(None, 'evaluations', type_='foreignkey')
    op.drop_column('evaluations', 'task_rating')
    # ### end Alembic commands ###
