"""user_id_to_id

Revision ID: d817b503d28b
Revises: 635ea08b1f7a
Create Date: 2025-09-18 18:50:16.259505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd817b503d28b'
down_revision: Union[str, Sequence[str], None] = '635ea08b1f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('evaluations_task_rating_fkey'), 'evaluations', type_='foreignkey')
    op.drop_column('evaluations', 'task_rating')
    op.drop_constraint(op.f('tasks_task_executor_fkey'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'task_executor')
    op.drop_constraint(op.f('teams_team_admin_fkey'), 'teams', type_='foreignkey')
    op.drop_column('teams', 'team_admin')
    op.add_column('users', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.drop_column('users', 'id')
    op.add_column('teams', sa.Column('team_admin', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('teams_team_admin_fkey'), 'teams', 'users', ['team_admin'], ['user_id'])
    op.add_column('tasks', sa.Column('task_executor', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('tasks_task_executor_fkey'), 'tasks', 'users', ['task_executor'], ['user_id'])
    op.add_column('evaluations', sa.Column('task_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('evaluations_task_rating_fkey'), 'evaluations', 'tasks', ['task_rating'], ['task_id'])
    # ### end Alembic commands ###
